# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Capstone' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'

  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  # Pods for Capstone
  pod 'Firebase/Core'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionTextModel'
  pod 'Firebase/MLVisionFaceModel'
  pod 'Firebase/MLVisionBarcodeModel'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionLabelModel'

end
